### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Lioniox** [Nitr4m12/UltimateBoTWConverter#2]
I'm new at modding Botw and needing help to by using this. I wanna install mods for wii u on my switch but I have no idea how to use this converter. And I don't understand the usage.

**Comment by Nitr4m12** [comment]
I want to make sure of a few before I can help you:
- Do you have the requirements installed? (i.e. do you have BCML set up)
- Do you have your mod packaged as a BNP?

**Comment by Lioniox** [comment]
No I didn't have BCML wait... I will install it now

**Comment by Lioniox** [comment]
I was modding it was no installer

**Comment by Lioniox** [comment]
And I have recently installed Phyton so I don't know how to use

**Comment by Nitr4m12** [comment]
You need to use `pip install bcml` in CMD to install it. You also need to make sure your python version is **NOT** 3.9 or above. You can check your python version in CMD as well, using `python -V`.

**Comment by Lioniox** [comment]
@Nitr4m12 I have downloaded BCML 3.7.1 but how can I install/open it?

**Comment by Nitr4m12** [comment]
Just running `bcml` in CMD should open it

**Comment by Lioniox** [comment]
It wasn't loading your comments now I can see them

**Comment by Lioniox** [comment]
Is CMD the normal command prompt from Windows

**Comment by Nitr4m12** [comment]
Yes

**Comment by Lioniox** [comment]
So I need to Launch Cmd from Windows normally? Because when I launch its showing C:/Users/user and then the command is it right? (I am really embarrassed to have so little idea)

**Comment by Nitr4m12** [comment]
Don't worry, we all start somewhere! And yes, that's how it should be.

**Comment by Lioniox** [comment]
So when its launched just copy `pip install bcml` in it?

**Comment by Nitr4m12** [comment]
Yes

**Comment by Lioniox** [comment]
It's sowing 
```
The command "pip" is misspelled or
could not be found.
```

**Comment by Nitr4m12** [comment]
Oh, I forgot to ask. When installing python, did you check "Add python ... to PATH"?

**Comment by Lioniox** [comment]
Sorry I was AFK but I'm back now

**Comment by Lioniox** [comment]
I will reinstall it and try to find this option

**Comment by Lioniox** [comment]
Oh, I didn't find this option but I find out how to open python and it1s showing

```
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by Nitr4m12** [comment]
Did you open it with just `python`?

**Comment by Lioniox** [comment]
What are you meaning? BCML? I'm thinking its better to go into a Discord call or not? Because then I can ask you directly.

**Comment by Nitr4m12** [comment]
We should be almost done with installing BCML. I was trying to ask if you opened python through CMD, because that would mean that python was added to PATH already.

**Comment by Lioniox** [comment]
No, I opened it directly.
I typed py in the search bar and opened the app that it was showing

**Comment by Nitr4m12** [comment]
Maybe this will help with BCML https://gamebanana.com/tools/7462. It's a script to auto-install BCML. It should work by just double-clicking.

**Comment by Lioniox** [comment]
Its installing

**Comment by Lioniox** [comment]
Installed. And now?

**Comment by Nitr4m12** [comment]
Was a shortcut created? If so, you can open it with that.

**Comment by Lioniox** [comment]
I creaded It and I opened it.

**Comment by Nitr4m12** [comment]
Okay. Somewhere along the setup process, it's going to ask for a dump of BotW. For that, you can follow this: https://zeldamods.org/wiki/Help:Dumping_games. Both this script and BCML need one to work properly (and using BCML to install your mods is highly recomended)

**Comment by Lioniox** [comment]
Ok let me configure Bcml

**Comment by Lioniox** [comment]
I'm going offline. I will reply when bcml is installed

**Comment by Lioniox** [comment]
@Nitr4m12 I'm online again but wich path should be in the bcml settings:
Base+Update Directory?

**Comment by Lioniox** [comment]
D:/atmosphere/contents/(botws game id)/romfs?
When I try to save these settings It's shows an error report

**Comment by Nitr4m12** [comment]
I think it would be better if you seeked help in [this](https://discord.gg/vPzgy5S) discord server, since your issue is more about the set up, rather than with the script. There's a bunch of people that should be able to help you better in there. I'll be closing this issue for now.

**Comment by Lioniox** [comment]
Ok, Thanks and sorry for the taking so much time!
