### ISSUE TITLE
ModuleNotFoundError: No module named 'bcml'

### ISSUE THREAD

**Issue by anthsalmo** [Nitr4m12/UltimateBoTWConverter#8]
Hi, Thanks for your efforts
I think this is an amazing Tool

However, each time I tried to convert a mod i faced the following issue

Attempting to convert 1 of 1 mods, please wait...

Traceback (most recent call last):
  File "/h/ubotwconverterv134/converter.py", line 20, in <module>
    from bcml.install import open_mod, find_modded_files
ModuleNotFoundError: No module named 'bcml'

Processed 1 mods.

- I have BCML 3.8.0, all settings for Switch
- I Dumped my own Zelda cartbrige v1.6.0
- Python 3.7.3

![001](https://user-images.githubusercontent.com/6970155/157359526-8b3b1b94-29f0-4317-8aeb-ca84511e6c46.PNG)
![002](https://user-images.githubusercontent.com/6970155/157359528-e4e69db1-3e8e-4608-8146-d95239f517d8.PNG)
![003](https://user-images.githubusercontent.com/6970155/157359530-1e6843cc-078e-43be-bdb2-04e50cc6b247.PNG)
![004](https://user-images.githubusercontent.com/6970155/157359532-acea6122-9d2c-4d4b-af14-c0cc5f372225.PNG)
![005](https://user-images.githubusercontent.com/6970155/157360031-2bb89606-8d4b-428b-af1a-745e971f3034.PNG)
![006](https://user-images.githubusercontent.com/6970155/157360032-64c06d64-21e5-41ac-ae9b-2c60e0593351.PNG)

**Comment by Nitr4m12** [comment]
Did you make sure to add your python installation to PATH?

**Comment by anthsalmo** [comment]
Yes, I did. I have been using BCML for Cemu since a few months ago. That is a prerequisite. But i want to use/port some mods for my Switch. Also I verified
![Capture](https://user-images.githubusercontent.com/6970155/157484487-b04a1924-1bf2-4982-8a14-cfb4a748d64b.PNG)
d

**Comment by Nitr4m12** [comment]
It looks like you have two python installations. Can you try uninstalling python 3.8, and rerun the script?

**Comment by anthsalmo** [comment]
I used to have Python 3.8 a long time ago. I downgraded it to 3.7.3 due a BCML issue, but it is no longer on my system since November 2021. I deleted the entries for Python 3.8 from Environment Variables and I ran the scripts but the issue still happens. 

However, The attached instructions works well. 
Running the command **convert_to_switch path/to/your/bnp** from CMD or PowerShell works  but your scripts doesn't work, I faced the same issue.

I tested with sockpoppets Tifa mod on my switch, it has textures issues, but I guess that happens because the tool doesn't support  *.Tex1.sbfres files

If you know about a tutorial how to port *.Tex1.sbfres and *.Tex2.sbfres to switch please let me know

Thanks for all your help!!!

![002](https://user-images.githubusercontent.com/6970155/157515500-11e5e154-665a-4adc-8125-1e1da37ed5a8.PNG)
o

**Comment by Nitr4m12** [comment]
I should've mentioned that using it that way gets you a prerelease, so there's still some things that wont work well (bfres conversion, for example). What happens when you run `pip show bcml` in cmd by the way? Or how about `python -V`?

**Comment by anthsalmo** [comment]
When I run the command, it showed the following. but is strange, that means It recognize BCML 3.9.9 instead 3.7.3? 

![005](https://user-images.githubusercontent.com/6970155/157569723-bf5967ba-1400-4af9-8fe9-0e7728a7a1d7.PNG)

**Comment by Nitr4m12** [comment]
It may be that you still have the one from the microsoft store, but this essentially means there's two versions of python installed in your system

**Comment by anthsalmo** [comment]
Thats is weird, I unnistalled Python 3.7.3 from windows program and features and reinstall it, and the script works!. I didn't do nothing more. I dont have a clue what happened between python versions. I am going to test the port. 
Thanks Again, for all your help! 

![006](https://user-images.githubusercontent.com/6970155/157576264-b770329a-3523-492c-b901-c1fbf3a5b1e7.PNG)
!

**Comment by anthsalmo** [comment]
I tested it.The script works perfectly. it is Awesome!. Thanks for your help and patience!
